export const USER_AUTHENTICATION = "USER_AUTHENTICATION";

export const ADD_CHARACTER = "ADD_CHARACTER";
export const DEL_CHARACTER = "DEL_CHARACTER";
export const SET_CHARACTER_DETAIL = "SET_CHARACTER_DETAIL";

export const ADD_FAVORITE = "ADD_FAVORITE";
export const DEL_FAVORITE = "DEL_FAVORITE";
export const FILTER_FAVORITES = "FILTER_FAVORITES";
export const ORDER_FAVORITES = "ORDER_FAVORITES";

export const CLEAN_FILTER_FAVORITES = "CLEAN_FILTER_FAVORITES";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const CLEAN_STATE = "CLEAN_STATE";